name: JSCPD Code Duplication Check

inputs:
  threshold:
    description: 'Threshold for JSCPD'
    required: true
    default: '2'
    type: string

outputs:
  duplicate-files:
    description: 'Number of duplicates found by JSCPD'
    value: ${{ steps.jscpd.outputs.duplicates }}

runs:
  using: 'composite'
  main: index.js
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Run JSCPD
      run: jscpd --reporters console,markdown,sarif --output report --threshold ${{ inputs.threshold }}

    - name: Upload JSCPD Report
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: jscpd-report
        path: report

    - name: Comment JSCPD results on PR
      if: success() || failure() && github.event_name == 'pull_request'
      uses: thollander/actions-comment-pull-request@v3
      with:
        file-path: report/jscpd-report.md
        comment-tag: jscpd-bot
