---
name: Call JSCPD Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  checks: write
  pull-requests: write

jobs:
  call-jscpd-action:
    name: Call JSCPD Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Call JSCPD Action
        uses: ./../../action.yml
        with:
          threshold: '3'
