name: Call JSCPD Action


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-jscpd-action:
    name: Call JSCPD Action
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: write
      contents: read
      id-token: read
      issues: read
      pull-requests: write
      statuses: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Call JSCPD Action
        uses: ./jscpd-action.yml
        with:
          threshold: '10'
